### ISSUE TITLE
Improvements in imports 

### ISSUE THREAD

**Issue by N0N4M3pl** [wisetime-io/grpc-web-rx#1]
Hi.

I'm testing your lib and I have found a problem.  
In `client.d.ts` and `retry.d.ts` you are using imports:  
`import Grpc from "grpc-web"; `

In my Angular project I'm also using grpc-web and during coding I have error:  

> Error: node_modules/grpc-web-rx/client.d.ts:1:8 - error TS1192: Module '"grpc-web"' has no default export.`
> import Grpc from "grpc-web";

After changing imports into:  
`import * as Grpc from "grpc-web";`
all works fine.

I'm using grpc-web package in version: `"grpc-web": "^1.2.1",`

**Comment by N0N4M3pl** [comment]
https://www.npmjs.com/package/grpc-web#typescript-support
There is example with:
`import * as grpcWeb from 'grpc-web';`

**Comment by j4ckofalltrades** [comment]
Thank you for raising an issue.

The reason why `import Grpc from "grpc-web"` works in this context is because the [allowSyntheticDefaultImports](https://github.com/wisetime-io/grpc-web-rx/blob/master/tsconfig.json#L13) flag is enabled.

As a workaround for the error you're encountering you can add `"allowSyntheticDefaultImports": true` under `compilerOptions` in your `tsconfig.json`, while this is being worked on.

Also one other thing, you don't need to add the `grpc-web` dependency to `package.json` if you've already added `grpc-web-rx`.

**Comment by N0N4M3pl** [comment]
Thanks for answer - you are right.
I didn't check your tsconfig.json.
Of course your sugestion works fine.
Thanks for help.
